SAPPHIRE_MAIN/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Sapphire.sitemaps import StaticViewsSitemap,Productsitemap1,Productsitemap2
from django.contrib.sitemaps.views import sitemap
from django.conf.urls import url 
from django.views.static import serve

sitemaps = {
    'sitemap' : StaticViewsSitemap,
    'Product_Type_1' : Productsitemap1,
    'Product_Type_2' : Productsitemap2,

}


urlpatterns = [
   # path('admin/',include('admin_honeypot.urls',namespace='admin_honey')),
    path('sapphire_main_secret_10101111/', admin.site.urls),
    path('',include('Sapphire.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap'), #this is straight from django docs
   
]
#if settings.DEBUG == True:
urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Sapphire/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.HomePage,name='Home'),
    path('AboutUs/',views.AboutUsPage,name='Aboutus'),
    path('products/',views.ProductPage,name='Product'),
    path('product_type1/<str:pk>',views.ProductType1,name='ProductType1'),
    path('product_type2/<str:pk>',views.ProductType2,name='ProductType2'),
    path('ourwork',views.OurWork,name='Ourwork'),
    path('ContactUs/',views.Contactus,name='contactus'),
    path('Brochure',views.Brochure_Page,name='Brochure'),
    path('download_pdf_file/<str:filename>', views.download_pdf_file,name='downloadPdfFile'),
   
]

Sapphire/models.py
from email import message
from django.db import models
from django.core.exceptions import ValidationError
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.safestring import mark_safe
from django.conf import settings
class SingleInstanceMixin(object):
    

    def clean(self):
        model = self.__class__
        if (model.objects.count() > 0 and self.id != model.objects.get().id):
            raise ValidationError("Can only create 1 %s instance" % model.__name__)
        super(SingleInstanceMixin, self).clean()

class ZeroInstanceMixin(object):
    
    def clean(self):
        model = self.__class__
        if (model.objects.count() > 0 and self.id != model.objects.get().id):
            raise ValidationError("Can only create 1 %s instance" % model.__name__)
        super(ZeroInstanceMixin, self).clean()

class Settings(SingleInstanceMixin,models.Model):
    Company_Name = models.CharField(max_length=225,default="Sapphire Commotrade Pvt.Ltd")
    Main_Logo = models.ImageField()
    
    Office_Address_Title = models.CharField(max_length=225 , default="Office Address")
    Office_Address1 = models.CharField(max_length=225,default="2nd Floor,New Golden Plaza,")
    Office_Address2 = models.CharField(max_length=225,default="Burdwan Road,")
    City_1 = models.CharField(max_length=64, default="Siliguri")
    Office_Address_Zip_Code = models.CharField(max_length=6, default="734001")



    Contact_Title = models.CharField(max_length=225,null=True,blank=True)
    Contact_Number_1 = PhoneNumberField()
    Contact_Number_2 = PhoneNumberField()
    Contact_Number_3 = PhoneNumberField()

    Email_Title = models.CharField(max_length=225,null=True,blank=True)
    Offical_Email_Id = models.EmailField()
    Offical_Information_Email_Id = models.EmailField()

    Facebook_Page_Link = models.URLField(max_length=225,null=True,blank=True)
    Instagram_Page_Link = models.URLField(max_length=225,null=True,blank=True)
    LinkedIn_Page_Link = models.URLField(max_length=225,null=True,blank=True)
    Twitter_Page_Link = models.URLField(max_length = 225,null = True,blank= True)

    Factory_Address_Title = models.CharField(max_length=255,default="Factory Address")
    Factory_Address1 = models.CharField(max_length=255,default="Demdema,Sanasekhata")
    Factory_Address2 = models.CharField(max_length=255,default="Bhutkihat,Rajgung,")
    City_2 = models.CharField(max_length=64, default="Jalpaiguri")
    Factory_Adress_Zip_Code = models.CharField(max_length=6, default="735135")


    Copyright_Field = models.CharField(max_length=225,default="2015 Sapphire Commotrade")

    Footor_Logo = models.ImageField()

    def Main_logo(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.Main_Logo.url))

    def Footor_logo(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.Footor_Logo.url))

  
   


    
    def __str__(self):
            return 'Settings'
    
    class Meta:
        verbose_name_plural = "        Settings"


class Home(SingleInstanceMixin,models.Model):
    
    Home_Top_Background_Image = models.ImageField()
    Welcome_Title = models.CharField(max_length=225)
    Welcome_Description = models.TextField()

    What_We_Offer_Title =  models.CharField(max_length=225)
    What_We_Offer_Description = models.TextField() 

    def __str__(self):
            return 'Home'    

    def Home_Top_Background_image(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.Home_Top_Background_Image.url))

    class Meta:
        verbose_name_plural = "       Home"  

        
              

class About(SingleInstanceMixin,models.Model):
    About_Us_Top_Background_Image = models.ImageField()
    About_Us_Title =  models.CharField(max_length=225)
    About_Us_Description = models.TextField(default='')

    OurStory_Title =  models.CharField(max_length=225)

    Where_It_All_Began_Title =  models.CharField(max_length=225)
    Where_It_All_Began_Description = models.TextField(default='')
    Where_It_All_Began_Image = models.ImageField()

    Our_Mission_Title =  models.CharField(max_length=225)
    Our_Mission_Description = models.TextField()

    Testimonial_Title =  models.CharField(max_length=225)

    What_People_Are_Saying_Title =  models.CharField(max_length=225)

    def About_Us_Top_Background_image(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.About_Us_Top_Background_Image.url))

    def Where_It_All_Began_image(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.Where_It_All_Began_Image.url))




    def __str__(self):
            return 'About Us'
    class Meta:
        verbose_name_plural = "      About"

      

class Testimonial(models.Model):

 

    Title =  models.CharField(max_length=225)
    Body = models.TextField()
    Full_Name = models.CharField(max_length=225)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add = True)

    class Meta:
     ordering = ['-updated', '-created']
     verbose_name_plural = "     Testimonials"


class Our_Works(models.Model):
        
        Image1 = models.ImageField(blank=True,null=True)
        Image2 = models.ImageField(blank=True,null=True)
        Image3 = models.ImageField(blank=True,null=True)

        def image1(self):
                return mark_safe('<img src="{}" width="100" />'.format(self.Image1.url))

        def image2(self):
                return mark_safe('<img src="{}" width="100" />'.format(self.Image2.url))

        def image3(self):
                return mark_safe('<img src="{}" width="100" />'.format(self.Image3.url))

        

        class Meta:
            verbose_name_plural = "  Our_Works"

    

class Product_Type_1(models.Model):
    Product_Name =models.CharField(max_length=225,null=True)
    Product_Short_Description_1 = models.CharField(max_length=225)
    Product_Top_Background_Image = models.ImageField()
    Product_Short_Description_2 = models.CharField(max_length=225)
    Product_HomePage_Image = models.ImageField(null=True,blank=True)
    Product_HomePage_Description = models.TextField(null=True , blank=True)
    Product_ProductPage_Image  =  models.ImageField(null=True,blank=True) 
    Product_ProductPage_Description = models.TextField(null=True,blank=True)
    Product_Middle_Image = models.ImageField()
    Visit_Our_Website_Title = models.CharField(max_length=225,default="Visit our website",null=True,blank=True)
    Website_Link = models.URLField(max_length=225,null=True,blank=True)
    To_Know_More_Visit_Our_Website = models.CharField(max_length=225,default="To know more visit our website",null=True,blank=True)
    Introduction_Section_Title = models.CharField(max_length=255) 
    Introduction_Section_Description = models.TextField()
    
    Introduction_Section_Image1 = models.ImageField()
    Introduction_Section_Image2 = models.ImageField()
    Why_Us_Title = models.CharField(max_length=225) 
    Why_Us_Description = models.TextField()
    Why_Us_Image1 = models.ImageField()
    Why_Us_Image2 = models.ImageField()
    Why_Us_Image3 = models.ImageField()
    
    Product_Structure_Image = models.ImageField()
    
    def Product_ProductPage_image(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.Product_ProductPage_Image.url))

    def Product_HomePage_image(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.Product_HomePage_Image.url))
    
    def Product_Top_Background_image(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.Product_Top_Background_Image.url))

    def Product_Middle_image(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.Product_Middle_Image.url))
    
    def Introduction_Section_image1(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.Introduction_Section_Image1.url))

    def Introduction_Section_image2(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.Introduction_Section_Image2.url))

    def Why_Us_image1(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.Why_Us_Image1.url))

    def Why_Us_image2(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.Why_Us_Image2.url))

    def Why_Us_image3(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.Why_Us_Image3.url))
        
    def Product_Structure_image(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.Product_Structure_Image.url))
          



    def __str__(self):
            return self.Product_Name
    class Meta:
         verbose_name_plural = "    Product_Type_1"    


class Product_Type1_Structure(models.Model):
    
    Product_name = models.ForeignKey(Product_Type_1 , on_delete=models.CASCADE)
    Product1_Structure_Title = models.CharField(max_length=225,null=True,blank=True,default='')
    Product1_Structure_Short_Description = models.TextField(null=True,blank=True)
   
 

class Product_Type1_Features(models.Model):
        Product_name = models.ForeignKey(Product_Type_1 , on_delete=models.CASCADE)
        ProductType1_Feature = models.CharField(max_length=225,null=True,blank=True)
     
class Product_Type1_Assurances(models.Model):
        Product_name = models.ForeignKey(Product_Type_1 , on_delete=models.CASCADE)
        ProductType1_Assurance = models.CharField(max_length=225,null=True,blank=True)
        
        
####### Product type 2 models starts form here ########
class Product_Type_2(models.Model):
   

    Product_Name = models.CharField(max_length=225,null=True)
    Product_Short_Description_1 = models.CharField(max_length=225)
    Product_Top_Background_Image = models.ImageField()
    Product_Short_Description_2 = models.CharField(max_length=225)
    Product_HomePage_Image = models.ImageField(null=True,blank=True) 
    Product_HomePage_Description = models.TextField(null=True , blank=True)
   

Sapphire/templates/Sapphire/AboutUs.html
{% extends 'main.html' %}
{%load static%}

{%block content%}
{%for obj in About_obj %}

<section class="background-image">
<!-- style="width: 100%;
height: 500px;
position: relative;
background-image: url('{{obj.About_Us_Top_Background_Image.url}}');
background-repeat: no-repeat;
background-size: cover;
background-position: center;"
> -->
    <!-- <img src="{{obj.About_Us_Top_Background_Image.url}}" alt="img"> -->
    <div class="aboutus">
        <h3>{{obj.About_Us_Title}}</h3>
        <p>{{obj.About_Us_Description|linebreaksbr}}</p>
    </div>
</section>


<section class="main-frame">
    <div class="content">
        <img src="{{obj.Where_It_All_Began_Image.url}}" alt="image">
        <div class="paragraph">
            <div class="ourstory">
                <p>{{obj.OurStory_Title}}</p>
            </div>
            <h3>{{obj.Where_It_All_Began_Title}}</h3>
            <p>{{obj.Where_It_All_Began_Description | linebreaksbr}}</p>
        </div>
    </div>
</section>

<div class="ourmission">
    <div class="ourmissionh1">
        <h3>{{obj.Our_Mission_Title}}</h3>
    </div>

    <div class="ourmissionpara">
        <p>{{obj.Our_Mission_Description|linebreaksbr}}</p>
    </div>
</div>

<div class="ratings">
    <div class="testimonals">
        <p>{{obj.Testimonial_Title}}</p>
    </div>
    <div class="rate-quote">
        <h3>{{obj.What_People_Are_Saying_Title}}</h3>
    </div>

    <div class="rate-row">
        {%for Testi in Testimonial_obj%}
        <div class="rate-col-1">
                <div class="rate-icons">
                    <img src="{% static 'images/star_3.png' %}" alt="">
                    <img src="{% static 'images/star_3.png' %}" alt="">
                    <img src="{% static 'images/star_3.png' %}" alt="">
                    <img src="{% static 'images/star_3.png' %}" alt="">
                    <img src="{% static 'images/star_3.png' %}" alt="">
                </div>

                <div class="rate-para">
                    <h3>{{Testi.Title}}</h3>
                    <p>{{Testi.Body}}</p>

                    <h3>{{Testi.Full_Name|linebreaksbr}}</h3>
                </div>
        </div>

        {%endfor%}
    </div>
</div>

{%endfor%}

{%endblock content%}

Sapphire/templates/Sapphire/Contactus.html
{%extends 'main.html'%}
{%load static%}
{%block content %}


<section class="contactlist">
<!-- style="width: 100%;
height: 350px;
position: relative;
background-image: url('{{contact.Background_Image.url}}');
background-repeat: no-repeat;
background-size: cover;
background-position: center;
"> -->
    {%for contact in contactus%}
	<!-- <img class = "contactlist-img" src=" {{contact.Background_Image.url}}" alt=""> -->
    <div class="contact">
        <div class="contactform">
            <div class="contactpara">
              
                <h3>{{contact.Title}}</h3>
                <p>{{contact.Description}}</p>
            </div>
      
            <div class="icons">
                <a href="#"><img src="{%static 'images/Facebook - Negative.png'%}" alt=""></a>
                <a href="#"><img src="{% static 'images/Instagram - Negative.png' %}" alt=""></a>
            </div>
           <form action="" method = "POST">
                {% csrf_token %}
             <input type="text" name="full_name" placeholder="Name">
             <input type="email" name="email" placeholder="Email">
             <input type="Number" name="phoneno" placeholder="Phone No.">
             <textarea name="help" id="textarea" cols="30" rows="10" placeholder="How can we help you out?"></textarea>
             
           
             <div class="g-recaptcha" data-sitekey="6LdhaM4hAAAAAFQvbmdBgxDSdKY7kfQJPeQSmQmH"></div>
             
             <button class="btn-contact" type = "submit" >Send</button>
           </form>
        </div>

        <div class="contactinfo">
            {%for setting in settings %}
            <div class="address">
                <div class="addressicon">
                    <img src="{%static 'images/pin.png' %}" alt="">
                    <h3>{{setting.Office_Address_Title}}</h3>
                </div>
                <ul>
                    <li>{{setting.Office_Address1}}</li>
                    <li>{{setting.Office_Address2}}</li>
                    <li>{{setting.City_1}} {{setting.Office_Address_Zip_Code}}</li>
                </ul>
            </div>

            <div class="Factoryaddress">
                <div class="factoryaddressicon">
                    <img src="{%static 'images/pin.png' %}" alt="">
                    <h3>{{setting.Factory_Address_Title}}</h3>
                </div>
                <ul>
                    <li>{{setting.Factory_Address1}}</li>
                    <li>{{setting.Factory_Address2}}</li>
                    <li>{{setting.City_2}} {{setting.Factory_Adress_Zip_Code}}</li>
                </ul>
            </div>

            <div class="phone">
                <div class="phoneicon">
                    <img src="{% static 'images/phone-call.png' %}" alt="">
                    <h3>{{setting.Contact_Title}}</h3>
                </div>
                <ul>
                    <li>{{setting.Contact_Number_1 }}</li>
                    <li>{{setting.Contact_Number_2 }}</li>
                    <li>{{setting.Contact_Number_3 }}</li>
                </ul>
            </div>

            <div class="emailus">
                <div class="emailusicon">
                    <img src="{% static 'images/email2.png' %}" alt="">
                    <h3>{{setting.Email_Title}}</h3>
                </div>
 
                <ul>
                   {{setting.Offical_Email_Id }}
                </ul>
            </div>
            {%endfor%}
        </div>
        {%endfor%}
    </div>
   
</section>  

 <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d28517.964718426567!2d88.38796356973268!3d26.688617936794593!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39e4434f73895953%3A0xe2b54ddd28caf18a!2sSapphire%20uPVC%20windows%20and%20doors%20-%20UPVC%20Window%20Manufacturers%20in%20Siliguri!5e0!3m2!1sen!2sin!4v1655998074888!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

{%endblock content%}

Sapphire/templates/Sapphire/EndsectionofEveryProduct.html
<section class="aboutproduct">
    {%for End_sec in End_Section %}
    <!-- <img src="{{End_sec.Background_Image.url}}" alt=""> -->
    <div class="quality">
       
        <div class="q1">
            <img src="{{End_sec.logo1.url}}" alt="img">
            <h3>{{End_sec.Title1}}</h3>
            <p>{{End_sec.Description1}}</p>
        </div>

        <div class="q1">
            <img src="{{End_sec.logo2.url}}" alt="img">
            <h3>{{End_sec.Title2}}</h3>
            <p>{{End_sec.Description2}}</p>
        </div>

        <div class="q1">
            <img src="{{End_sec.logo3.url}}" alt="img">
            <h3>{{End_sec.Title3}}</h3>
            <p>{{End_sec.Description3}}</p>
        </div>
        {%endfor%}
    </div>
</section>

Sapphire/templates/Sapphire/Home.html
{%extends 'main.html'%}

{%block content%}

{%for obj in Home_obj %}  
    
<section>
    <div class="background">
    <!-- style="width: 100%;
    height: 600px;
    position: relative;
    background-image: url('{{obj.Home_Top_Background_Image.url}}');
    background-repeat: no-repeat;
    background-size: cover;
    background-position: center; 
    @media (max-width: 630px)
    {
    width: 100%;
    height: 450px; 
    } "> -->
        <!-- <img src="{{obj.Home_Top_Background_Image.url}}" alt="img"> -->
        <div class="para">
            <h3>{{obj.Welcome_Title}}</h3>
            <p>{{obj.Welcome_Description}}</p>
        </div>
    </div>

</section>

<main class="container-fluid">
    <div class="main-q">
        <h3>{{obj.What_We_Offer_Title}}</h3>
        <p>{{obj.What_We_Offer_Description}}</p>
    </div>

{%for product2 in Product2|slice:":1"%}
  
    <div class="row-l">
        <div class="col-1">
            <div class="card1">
                <div class="card-head">
                    <h3>{{product2.Product_Name}}</h3>
                </div>
                <div class="card-body">
                    <p>{{product2.Product_HomePage_Description}}</p>
                </div>
                <div class="card-footer">
                    <button class="btn-learnmore"><a href="{%url 'ProductType2' product2.id %}">Read More</a></button>
                </div>
            </div>

            <div class="img">
                <img src="{{product2.Product_HomePage_Image.url}}" alt="">
            </div>
        </div>
    </div>



  
{%endfor%}

{%for product1 in Product1|slice:":1"%}
<div class="row-l">
    <div class="col-2">
        <div class="card2">
            <div class="card-head">
                <h3>{{product1.Product_Name}}</h3>
            </div>
            <div class="card-body">
                <p>{{product1.Product_HomePage_Description}}</p>
            </div>

            <div class="card-footer-2">
                <button class="btn-learnmore2"><a href="{%url 'ProductType1' product1.id %}">Read More</a></button>
            </div>
        </div>

        <div class="img">
            <img src="{{product1.Product_HomePage_Image.url}}" alt="">
        </div>
    </div>
</div>
{%endfor%}


{%for product1 in Product1|slice:"1:2"%}
  
    <div class="row-l">
        <div class="col-1">
            <div class="card1">
                <div class="card-head">
                    <h3>{{product1.Product_Name}}</h3>
                </div>
                <div class="card-body">
                    <p>{{product1.Product_HomePage_Description}}</p>
                </div>
                <div class="card-footer">
                    <button class="btn-learnmore"><a href="{%url 'ProductType1' product1.id %}">Read More</a></button>
                </div>
            </div>

            <div class="img">
                <img src="{{product1.Product_HomePage_Image.url}}" alt="">
            </div>
        </div>
    </div>



  
{%endfor%}


</main>





{%endfor%}



{%endblock content%}

Sapphire/templates/Sapphire/OurWork.html
{%extends 'main.html'%}

{%block content%}
    
<section class="ourwork">
    
    <section class="ourwork">
        {%for ourwork in Our_works%}
        <div class="row-ourwork">
            
            {%if ourwork.Image1%}
            <div class="col-ourwork">
                <img src="{{ourwork.Image1.url}}" alt="">
            </div>
            {%endif%}

            {%if ourwork.Image2 %}
            <div class="col-ourwork">
                <img src="{{ourwork.Image2.url}}" alt="">
            </div>
            {%endif%}
            {%if ourwork.Image3%}
            <div class="col-ourwork">
                <img src="{{ourwork.Image3.url}}" alt="">
            </div>
         {%endif%}
        </div>
        {%endfor%}

</section>

</section>

{%endblock content%}

Sapphire/templates/Sapphire/ProductType1.html
{%extends 'main.html'%}
{%load static%}
{%block content %}


{%for product1 in Product1 %}
<section class="pvcprofile">

<img src="{{product1.Product_Top_Background_Image.url}}" alt="img">

    <!-- class here is different you are looking at product_type2 class even though it is product_type1-->
    <div class="profile">
        <!-- <h3>{{product1.Product_Name|ljust:"7"}}</h3> -->
        <div class="heading">

            {%if product1.Product_Name|lower == 'sapphire floors' %}
            <h3>{{product1.Product_Name|slice:":9"}}</h3>
            <h3>{{product1.Product_Name|slice:"9:"}}</h3>
            {%else%}
                <h3>{{product1.Product_Name|slice:":5"}}</h3>
                <h3>{{product1.Product_Name|slice:"5:"}}</h3>
            {%endif%}
        </div>
        <p>{{product1.Product_Short_Description_1}}</p>
        {%if product1.Website_Link%}
        <button class="btn-more">{{product1.Website_Link}}</button>
        {%endif%}
    </div>
</section>


<div class="door-row1">
    <div class="col-door1">
        <h4>{{product1.Product_Name}}</h4>
        <p>{{product1.Product_Short_Description_2}}</p>
    </div>
</div>

<section class="profile-container">
    <img src="{{product1.Product_Middle_Image.url}}" alt="">
</section>


<div class="content-profile">
    <div class="content1">
        <h3>{{product1.Introduction_Section_Title }}</h3>

        <p>{{product1.Introduction_Section_Description|linebreaksbr}}</p>

            <ul class = "features-product-type" type = "square">

                {% for features in product1.product_type1_features_set.all%}   
                <li>{{features.ProductType1_Feature}}</li>
                {% endfor %} 
           
            </ul>
    </div>

    <div class="content2">
   
        <div class="content-images2">
            <img src="{{product1.Introduction_Section_Image1.url }}" alt="">
            <img src="{{product1.Introduction_Section_Image2.url }}" alt="">
        </div>
        <ul class="listtype2">
        {% for Assurance in product1.product_type1_assurances_set.all%}   
         <li><img src="{%static 'images/check.png' %}" alt="">{{Assurance.ProductType1_Assurance }}</li>
        {% endfor %} 
        <ul>

    </div>
</div>

<div class="structure">
    <div class="structure-img">
        <img src="{{product1.Product_Structure_Image.url}}" alt="img">
    </div>

    <div class="structure-content">
        {% for structure in product1.product_type1_structure_set.all%} 
        {%if structure.Product1_Structure_Title %}  
        <h4>{{structure.Product1_Structure_Title }}</h4>
        {%endif%}

        {%if structure.Product1_Structure_Short_Description %}
        <p>{{structure.Product1_Structure_Short_Description}}</p>
        {%endif%}
        {%endfor%} 

       
    </div>
</div>

<section class="whyus">
    <div class="door-whyus-img">
        <img src="{{product1.Why_Us_Image1.url}}" alt="img">
        <img src="{{product1.Why_Us_Image2.url}}" alt="img">
        <img src="{{product1.Why_Us_Image3.url}}" alt="img">
    </div>

    <div class="whyus-content">
        <h3>{{product1.Why_Us_Title}}</h3>
        <p>{{product1.Why_Us_Description|linebreaksbr}}</p>
    </div>
</section>




{%include 'Sapphire/EndsectionofEveryProduct.html'%}
{%endfor%}
{%endblock content %}

Sapphire/templates/Sapphire/Products.html
{%extends 'main.html'%}
{%block content %}




    
<section class="products">
    <div class="productsh1">
        <h3>OUR PRODUCTS</h3>
    </div>

    
    <div class="product-card">
        {%for product2 in Product2%}
        <div class="card-pro">
            <img src="{{product2.Product_ProductPage_Image.url}}" alt="">

            <div class="card-pro-para">
                <h3>{{product2.Product_Name}}</h3>
                <p>{{product2.Product_ProductPage_Description}}</p>
                <button class="btn-read-more"><a href="{%url 'ProductType2' product2.id %}">READ MORE</a></button>
            </div>
       
        </div>
        {%endfor%}
    
    {%for product1 in Product1%}
        <div class="card-pro">
            <img src="{{product1.Product_ProductPage_Image.url}}" alt="">

            <div class="card-pro-para">
                <h3>{{product1.Product_Name}}</h3>
                <p>{{product1.Product_ProductPage_Description}}</p>
                <button class="btn-read-more"><a href="{%url 'ProductType1' product1.id %}">READ MORE</a></button>
            </div>

        </div>
        {%endfor%}

      
    </div>
</section>

{%include 'Sapphire/EndsectionofEveryProduct.html'%}

{%endblock content %}